Online-Ordering-Food/Online-Ordering-Food/Controllers/ResturantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Online_Ordering_Food.Models;
using System.IO;
using Online_Ordering_Food.ViewModel;

namespace Online_Ordering_Food.Controllers
{
    public class ResturantController : Controller
    {
        private ResturantEntities db = new ResturantEntities();

        public ActionResult OOFMenu()
        {
            var viewmodel = new ProductCart()
            {
                products = db.Products.Include(p => p.Category).ToList(),
                carts = db.Carts.Include(c => c.Product).ToList()
            };
            //var products = db.Products.Include(p => p.Category);
            return View(viewmodel);
        }
        [HttpPost]
        public ActionResult OOFMenu(string SearchTerm)
        {

            var viewmodel = new ProductCart()
            {
                products = db.Products.Include(p => p.Category).ToList(),
                carts = db.Carts.Include(c => c.Product).ToList()
            };
            if (string.IsNullOrEmpty(SearchTerm))
            {
                viewmodel.products = db.Products.Include(p => p.Category).ToList();
            }
            else
            {
                viewmodel.products = db.Products.Include(p => p.Category).Where(a => a.Category.Category_Name.ToLower().StartsWith(SearchTerm.ToLower())).ToList();
            }
            return View(viewmodel);
        }

        // Menu page
        public ActionResult Menu()
        {

            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        [HttpPost]
        public ActionResult Menu(string SearchTerm)
        {
            List<Product> products;
            if (string.IsNullOrEmpty(SearchTerm))
            {
                products = db.Products.Include(p => p.Category).ToList();
            }
            else
            {
                products = db.Products.Include(p => p.Category).Where(a => a.Category.Category_Name.ToLower().StartsWith(SearchTerm.ToLower())).ToList();
            }
            return View(products);
        }

        public ActionResult MenuDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //public ActionResult OOFMenu()
        //{

        //    var products = db.Products.Include(p => p.Category);
        //    return View(products.ToList());
        //}

        //[HttpPost]
        //public ActionResult OOFMenu(string SearchTerm)
        //{
        //    List<Product> products;
        //    if (string.IsNullOrEmpty(SearchTerm))
        //    {
        //        products = db.Products.Include(p => p.Category).ToList();
        //    }
        //    else
        //    {
        //        products = db.Products.Include(p => p.Category).Where(a => a.Category.Category_Name.ToLower().StartsWith(SearchTerm.ToLower())).ToList();
        //    }
        //    return View(products);
        //}

        public ActionResult OOFMenuDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }


        //Home Page:
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult OOFHome()
        {
            return View();
        }

        //Regestration Page
        [HttpGet]
        [ActionName("Regestration")]
        public ActionResult Regestration_Get()
        {
            return View();
        }


        [HttpPost]
        [ActionName("Regestration")]
        public ActionResult Regestration_Post(UserInfo user)
        {
            using (ResturantEntities db = new ResturantEntities())
            {
                if (db.UserInfoes.Any(x => x.username == user.username) || db.UserInfoes.Any(y => y.EmailAddress == user.EmailAddress))
                {
                    ViewBag.message = "UserName OR Email Already Exist";
                    return View(user);
                }
                else
                {
                    db.UserInfoes.Add(user);
                    db.SaveChanges();
                }

            }
            return RedirectToAction("LogIn");
        }

        //login page
        [HttpGet]
        [ActionName("LogIn")]
        public ActionResult LogIn_Get()
        {

            return View();
        }

        [HttpPost]
        [ActionName("LogIn")]
        public ActionResult LogIn_Post(UserInfo user)
        {
            ResturantEntities db = new ResturantEntities();

            if ((user.username == "admin") && (user.Password == "admin1234"))
            {
                return RedirectToAction("AdminDashboard");
            }
            else if (db.UserInfoes.Any(x => x.username == user.username) && db.UserInfoes.Any(y => y.Password == user.Password))
            {
                return RedirectToAction("OOFHome");
            }
            else
            {
                ViewBag.message = "username or Password is INCORRECT";
                return View(user);
            }
        }


        // admin pages
        public ActionResult AdminDashboard()
        {
            return View();
        }

        //ProductDetails Page
        public ActionResult ProductDetails()
        {

            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        [HttpPost]
        public ActionResult ProductDetails(string SearchTerm)
        {
            List<Product> products;
            if (string.IsNullOrEmpty(SearchTerm))
            {
                products = db.Products.Include(p => p.Category).ToList();
            }
            else
            {
                products = db.Products.Include(p => p.Category).Where(a => a.Category.Category_Name.ToLower().StartsWith(SearchTerm.ToLower())).ToList();
            }
            return View(products);
        }
        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // CreateProduct page
        public ActionResult Create()
        {
            ViewBag.Category_id = new SelectList(db.Categories, "Id", "Category_Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Image,Description,Category_id")] Product product, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                product.Image = upload.FileName;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("ProductDetails");
            }

            ViewBag.Category_id = new SelectList(db.Categories, "Id", "Category_Name", product.Category_id);
            return View(product);
        }

        // UpdateProduct Page
        public ActionResult UpdateProduct()
        {

            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        [HttpPost]
        public ActionResult UpdateProduct(string SearchTerm)
        {
            List<Product> products;
            if (string.IsNullOrEmpty(SearchTerm))
            {
                products = db.Products.Include(p => p.Category).ToList();
            }
            else
            {
                products = db.Products.Include(p => p.Category).Where(a => a.Category.Category_Name.ToLower().StartsWith(SearchTerm.ToLower())).ToList();
            }
            return View(products);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category_id = new SelectList(db.Categories, "Id", "Category_Name", product.Category_id);
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Image,Description,Category_id")] Product product, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                product.Image = upload.FileName;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ProductDetails");
            }
            ViewBag.Category_id = new SelectList(db.Categories, "Id", "Category_Name", product.Category_id);
            return View(product);
        }

        // DeleteProduct Page

        public ActionResult DeleteProduct()
        {

Online-Ordering-Food/Online-Ordering-Food/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online-Ordering-Food", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin Home", "AdminDashboard", "Resturant")</li>
                    <li>@Html.ActionLink("Add Product", "Create", "Resturant")</li>
                    @*<li>@Html.ActionLink("Products", "Index", "Resturant")</li>*@
                    <li>@Html.ActionLink("Update Product", "UpdateProduct", "Resturant")</li>
                    <li>@Html.ActionLink("Delete Product", "DeleteProduct", "Resturant")</li>
                    <li>@Html.ActionLink("Product Detials", "ProductDetails", "Resturant")</li>
                    @*<li>@Html.ActionLink("Shopping Cart", "Index", "Products")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Online-Ordering-Food/Online-Ordering-Food/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online-Ordering-Food", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Resturant")</li>

                    <li>@Html.ActionLink("Menu", "Menu", "Resturant")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Online-Ordering-Food/Online-Ordering-Food/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online-Ordering-Food", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "OOFHome", "Resturant")</li>

                    <li>@Html.ActionLink("Menu", "OOFMenu", "Resturant")</li>
                    <li> <a class="navbar-brand" data-target="#CartModal" data-toggle="modal">Show Cart</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>